updated db
mtalstykh-exadel/team4_docs pull request #2
Opened 2021-07-09 21:17 UTC by Darina007

2021-07-10 04:14 UTC, AntonMaksimenkau approved these changes

2021-07-10 04:31 UTC, AntonMaksimenkau requested changes
Please, update a screenshot as well

2021-07-11 17:51 UTC, AntonMaksimenkau approved these changes

2021-07-11 18:11 UTC, Anlord241 approved these changes

2021-07-11 18:23 UTC, merged