Docs: crud for file answers
mtalstykh-exadel/team4_docs pull request #7
Opened 2021-07-22 10:45 UTC by SemyonKorostik

2021-07-22 12:46 UTC, AntonMaksimenkau requested changes

2021-07-22 12:46 UTC, AntonMaksimenkau commented on getting started/backend/file_answer.md
> +`POST` | `/file_answer/`| `JSON-object` | `200 OK`/`500 Internal Server Error`
5xx should never been throwed

2021-07-22 12:46 UTC, AntonMaksimenkau commented on getting started/backend/file_answer.md
> +#Update file answer
Please, mark update and delete methods as experemental

2021-07-22 13:53 UTC, AntonMaksimenkau approved these changes

2021-07-23 08:54 UTC, maxim12321 approved these changes

2021-07-23 15:47 UTC, merged