update db docs
mtalstykh-exadel/team4_docs pull request #8
Opened 2021-07-22 15:08 UTC by Darina007

2021-07-22 15:26 UTC, AntonMaksimenkau requested changes
we don't need the sql file anymore as we are using liquibase. You can just delete it

2021-07-22 15:28 UTC, maxim12321 submitted a review, later dismissed

2021-07-22 20:00 UTC, maxim12321 approved these changes

2021-07-23 06:45 UTC, AntonMaksimenkau approved these changes

2021-07-23 08:52 UTC, merged